### ISSUE TITLE
Creating registrar without IANA ID is failing

### ISSUE THREAD

**Issue by olofvndrhr** [peteeckel/netbox-plugin-dns#100]
**Versions**
NetBox Version: 3.6.5
NetBox DNS Version: 0.21.0
Python Version: 3.11.4

**Describe the bug**
When creating a new registrar without an IANA ID, a Netbox Error is thrown.

**To Reproduce**
1. Try to create a new Registrar just with the name
2. Click create

**Expected result**
No error as the field is not mandatory in the form.

**Actual result**
The error is thrown.

**Screenshots**
![Screenshot 2023-11-16 144710](https://github.com/peteeckel/netbox-plugin-dns/assets/68583543/9d38769c-10f7-49e6-8f97-91cd0816763d)
![Screenshot 2023-11-16 144728](https://github.com/peteeckel/netbox-plugin-dns/assets/68583543/41aec391-f3b5-454c-976e-3194034323fd)

**Comment by peteeckel** [comment]
Oops - true. Obviously something failed when I squashed the migrations.

**Comment by peteeckel** [comment]
The problem was that null must be allowed explicitly for Integer values ... fixed that.

**Comment by olofvndrhr** [comment]
Super, thanks for the quick fix!
