### ISSUE TITLE
SRV record will not take non-integers under "Value"

### ISSUE THREAD

**Issue by mrth3p1auge** [peteeckel/netbox-plugin-dns#103]
**Versions**
NetBox Version: 3.6.6
NetBox DNS Version: 0.21.3
Python Version: 3.11.6

**Describe the bug**
SRV records will not take non-integers in "Value"

**To Reproduce**
1. Go to 'zone,'
2. Click on 'recorders under the zone  and add new record'
3. Scroll down to 'Under Value enter a name like CNAME would have'
4. Error: "Record value sipdir.skypeforbusiness.net is not a valid value for a SRV record: expecting an integer."

**Expected result**
The Value should take an entry like CNAME

**Actual result**
System errors /

**Screenshots**

**Comment by peteeckel** [comment]
> Error: "Record value sipdir.skypeforbusiness.net is not a valid value for a SRV record: expecting an integer."

This is true. `SRV records require a priority, a weight and a port number, all of which are integer values. `sipdir.skypeforbusiness.net` is indeed not a valid `SRV` record value.

Anyway, if this error actually were a bug, it would be one in `dnspython`. As it is, it is correct behaviour.

**Comment by KPTheProf** [comment]
Hi, I think you are missing that that data also contains a target ( the canonical hostname of the machine providing the service, ending in a dot.)

From https://en.wikipedia.org/wiki/SRV_record

A Service record (SRV record) is a specification of data in the [Domain Name System](https://en.wikipedia.org/wiki/Domain_Name_System) defining the location, i.e., the hostname and port number, of servers for specified services. It is defined in [RFC 2782](https://datatracker.ietf.org/doc/html/rfc2782), and its type code is 33. Some Internet protocols such as the [Session Initiation Protocol](https://en.wikipedia.org/wiki/Session_Initiation_Protocol) (SIP) and the [Extensible Messaging and Presence Protocol](https://en.wikipedia.org/wiki/Extensible_Messaging_and_Presence_Protocol) (XMPP) often require SRV support by network elements.

A SRV record has the form:

_service._proto.name. ttl IN SRV priority weight port target.

- service: the symbolic name of the desired service.
- proto: the transport protocol of the desired service; this is usually either [TCP](https://en.wikipedia.org/wiki/Transmission_Control_Protocol) or [UDP](https://en.wikipedia.org/wiki/User_Datagram_Protocol).
- name: the domain name for which this record is valid, ending in a dot.
- ttl: standard DNS [time to live](https://en.wikipedia.org/wiki/Time_to_live) field.
- IN: standard DNS class field (this is always IN).
- SRV: Type of Record (this is always SRV).
- priority: the priority of the target host, lower value means more preferred.
- weight: A relative weight for records with the same priority, higher value means higher chance of getting picked.
- port: the TCP or UDP port on which the service is to be found.
- target: the canonical hostname of the machine providing the service, ending in a dot.

An example SRV record in textual form that might be found in a [zone file](https://en.wikipedia.org/wiki/Zone_file) might be the following:

_sip._tcp.example.com. 86400 IN SRV 0 5 5060 sipserver.example.com.

**Comment by KPTheProf** [comment]
Apologies for that peter, I was using an extract from get-DnsServerResourceRecord where the SRV record data fields are separated by square brackets [ ]. Removing those and using a space character as the field separator allowed me to import the SRV data successfully.
