### ISSUE TITLE
Using IPAM-DNS coupling from a custom script

### ISSUE THREAD

**Issue by guilhemurroz** [peteeckel/netbox-plugin-dns#105]
**Versions**
NetBox Version: 3.6.3
NetBox DNS Version: [65d9cd5](https://github.com/peteeckel/netbox-plugin-dns/commit/65d9cd5fe3131b58c09ce08ae5bfb175c943c5c5)
Python Version: 3.8.10

**Describe the bug**
When I try to use the IPAM-DNS coupling inside a custom script, the DNS name is not updated and no DNS Record is created. It looks like signals (pre_save, ...) are not triggered.

**To Reproduce**
1. Create à custom script using and saving an IPAddress object
2. Execute the script

**Expected result**
The DNS Name of the IPAdress object must be updated.
A DNS record must be created

**Actual result**
- DNS name is not updated
- no DNS Record is created

**Code Examples**

```
from netaddr import IPNetwork
from ipam.models import IPAddress
from extras.scripts import Script, IPAddressVar, StringVar, ObjectVar
from netbox_dns.models import Zone

class Test(Script):
    class Meta:
        name = "Test"
        commit_default = True

    hostname = StringVar(
        label="Hostname",
        required=True
    )

    zone = ObjectVar(
        label="Zone",
        model=Zone,
        required=True
    )

    ip_address = IPAddressVar(
        label="IP Address",
        required=True
    )

    def run(self, data, commit):

        self.log_info("Test")

        IPAddress(
                address=IPNetwork(data['ip_address']),
                custom_field_data={
                    "ipaddress_dns_record_name": data['hostname'],
                    "ipaddress_dns_zone_id": data['zone'].id,
                }
        ).save()
```

**Comment by peteeckel** [comment]
Hi @guilhemurroz, you're right, this is an issue in the implementation currently in place. 

Would you be able to check if the latest PR #102 fixes the issue for you? The problem was the implementation as middleware, which did not catch for updates using the model methods directly (such as scripts do).

I'm planning to release #102 soon, but if you can test it before that would be great.

**Comment by guilhemurroz** [comment]
Hi @peteeckel, I'm afraid the problem is not solved yet and I don't understand why. Your explanations  and code look crystal clear but the signals are still not triggered. It exceeds my poor django capabilities :(

**Comment by peteeckel** [comment]
I just ran your script and it executes just fine - so something might be missing in your setup.

* Did you restart NetBox after adding the PR patch to your setup?
* Did you set the `feature_ipam_coupling` flag in the configuration?
* Did you create the custom fields using `manage.py setup_coupling`?

If you did all of this it **should** work - if it still doesn't, we need to dig a bit deeper.

**Comment by peteeckel** [comment]
Hi @guilhemurroz, did you get an opportunity to have a look at this? If not or if I don't hear from you, I will push PR #102 soon so the other issues with the existing code base are settled.

Feel free to re-open the issue if it does not help in your case so we can investigate more deeply.

**Comment by guilhemurroz** [comment]
@peteeckel, thant you for your answers. I have checked all the steps you mentionned, but was not able to make it work. I'm probably missing something out... Unfortunately I have not enough time to investigate more deeply now.

**Comment by peteeckel** [comment]
@guilhemurroz, for a moment I was surprised to find that I could reproduce your problem. Then I noticed that I was on the `main` branch, not on `fix/ipam-coupling-model`.

With the code of the latter branch, your script works like a charm. I'll create a new release now.

**Comment by peteeckel** [comment]
Release 0.21.8 has been published.

I verified that your script code works with this release.
