### ISSUE TITLE
Not a valid DNS hostname when saving TXT record with underscores.

### ISSUE THREAD

**Issue by KPTheProf** [peteeckel/netbox-plugin-dns#106]
**Versions**
NetBox Version: 3.6.6
NetBox DNS Version: 0.21.3
Python Version: 3.12.0

**Describe the bug**
Trying to add a TXT record for DKIM with the Name 'key1_op16._domainkey' and getting error "Not a valid DNS hostname".

I have the following PLUGINS_CONFIG set.

PLUGINS_CONFIG = {
  "netbox_dns": {
    "tolerate_underscores_in_hostnames": True,
    "tolerate_leading_underscore_types": [
      "TXT",
      "SRV",
    ],
    "tolerate_non_rfc1035_types": []
  }
}

**To Reproduce**
1. Go to 'Netbox DNS' 'Records' '+'
2. Fill in the details with the Name field set to 'key1_op16._domainkey'

If I change the Name to 'key1-op16._domainkey' it will save.

**Expected result**
 It appears to be an issue with underscores in TXT records, as I can save other record types with underscore in the name.

![Screenshot 2023-12-14 160742](https://github.com/peteeckel/netbox-plugin-dns/assets/56978198/86de71c5-da13-4560-b392-04b57c41af2e)

**Comment by peteeckel** [comment]
Interesting one, thanks ... can you try the following config to narrow it down, please:
```
PLUGINS_CONFIG = {
    "netbox_dns": {
        "tolerate_underscores_in_hostnames": True,
        "tolerate_leading_underscore_types": [],
        "tolerate_non_rfc1035_types": []
    }
}
```
If that should work I'm pretty sure I know where to look (and you have a workaround, too :-)).

**Comment by peteeckel** [comment]
0.21.4 has just been released with the fix.
