### ISSUE TITLE
Add Record Type Filter

### ISSUE THREAD

**Issue by KPTheProf** [peteeckel/netbox-plugin-dns#109]
**Is your feature request related to a problem? Please describe.**
I'm trying to find records of a particular type as TXT  or SRV

**Describe the solution you'd like**
Add a Type filter to the Records attribute filters tab.

**Describe alternatives you've considered**
There doesn't appear to be any way to filter on just the record type.

**Additional context**

![Screenshot 2023-12-19 105116](https://github.com/peteeckel/netbox-plugin-dns/assets/56978198/a5ea272e-e00f-4bb3-b0f6-57f8be4f0e7b)

**Comment by peteeckel** [comment]
Hi @KPTheProf, thanks fir reporting this ... I would have sworn the type filter has been there fir a long time, but in fact it isn't.

Might take a couple of days though as I'm currently quite busy.

**Comment by peteeckel** [comment]
That's what I suspected ... it's just missing from the filter view. Actually a trivial fix.

**Comment by peteeckel** [comment]
A bit embarrassing ... everything was in place, except the reference to the type filter in the fieldset ...
