### ISSUE TITLE
CSV import with tags not setting tags

### ISSUE THREAD

**Issue by KPTheProf** [peteeckel/netbox-plugin-dns#110]
**Versions**
NetBox Version: 3.6.7
NetBox DNS Version: 0.21.4
Python Version: 3.12.0

**Describe the bug**
When importing data using CSV import with a tags field with valid tag data, it is not adding the tags. I can add the same tags manually after the data has been imported.

**To Reproduce**
1. Go to Record Bulk Import
2. Add the below data (pasted from Excel in CSV tab separated format) with a valid tags field entry and import it. (Note that I've changed the domain names in the below example to hide my actual domains.)
3. The same issue happens importing from a comma separated CSV file.
4. I am able to import other netbox records (IP address) with the same tag field successfully.

zone	name	ttl	type	value	status	tags
uk.domain.biz	test-kp	3600	CNAME	web0.domain.co.uk.	active	dns-static

**Expected result**
Expect to the see the imported data with the correct tag field added.

**Actual result**
The record is imported except that the tag field is empty.

**Screenshots**

![Screenshot 2023-12-19 144128](https://github.com/peteeckel/netbox-plugin-dns/assets/56978198/ebfa91c5-49ea-49cf-97da-a3986072b3b3)

![Screenshot 2023-12-19 144345](https://github.com/peteeckel/netbox-plugin-dns/assets/56978198/c88e0db3-c58e-4572-bf39-5cda436fdb18)

**Comment by peteeckel** [comment]
Hi @KPTheProf, thanks for reporting! I can reproduce it - will look into what's causing this problem soon.

**Comment by peteeckel** [comment]
This issue is even better than I initially thought ...

Turned out that it wasn't only a problem with records, but also with zones, name servers and views. The origin of this lay in the very beginning of the predecessor `netbox-dns` (even before I started working on it), and obviously over more than two years nobody (including myself) ever noticed it.

**Comment by KPTheProf** [comment]
@peteeckel Hi Peter, I can confirm that this issue is now resolved , along with the other issues that I've reported recently.
I would just like to say a big "Thank You" for all the support and hard work that you've given on this great project.
I trust that you and yours will have a wonderful (and relaxing!) Christmas holiday period.  🎄 🎅 😄

**Comment by peteeckel** [comment]
Hi @KPTheProf, the best wishes for you and those around you, too!

Maintaining such a project wouldn't be half the fun weren't it for the people using it and contributing to it - and good issues are a contribution that can't be overrated. So thanks to you and all the other contributors, too! I hope to see you all again next year.
