### ISSUE TITLE
Record(s) don't allow char "_" for exaple in _dmarc

### ISSUE THREAD

**Issue by Xemanth** [peteeckel/netbox-plugin-dns#116]
**Versions**
NetBox Version: 3.6.6
NetBox DNS Version:  latest
Python Version: x.x.x

**Describe the bug**
When I add a record which has name "_dmarc", it gives an error.
If I remember _ char from it, it allows it to be saved.

**To Reproduce**
Just type as record _dmarc.

**Expected result**
It should allow it to be saved, _ is valid symbol in the records.

**Actual result**
A clear and concise description of what happens instead. If there are any exceptions or errors in the logs please provide them as well.

**Screenshots**

**Code Examples**
If applicable, please provide ideally minimal code example of code that is causing the problem to happen. The more concise the example is, the less effort it is to find a problem.

**Comment by peteeckel** [comment]
Hi @Xemanth, could you please post the full record. 

By default, leading underscores are allowed in `TXT` and `SRV` records. So a regular `_dmarc` record (which is of type `TXT`) should work.

**Comment by Xemanth** [comment]
Ah yea so it seems!👀

But in my use case, we have _dmarc record, which is CNAME type, and that record points to the external partner's DNS.
That external partner holds our dmarc txt record. 😵‍💫

**Comment by peteeckel** [comment]
There's a solution for that as well. 

Have a look at the documentation - you can use the variable `tolerate_leading_underscore_types` to set a list of record types that allow leading underscores. If you want to enable them for `CNAME` records, you can do this with the following config in `configuration.py`:

```
PLUGINS_CONFIG = {
    'netbox_dns': {
        'tolerate_leading_underscore_types': ["TXT", "SRV", "CNAME"]
    },
}
```

**Comment by Matt-Heltsley** [comment]
Thank you!  That fixed it for me.
