### ISSUE TITLE
Add a Azure Alias Records record type

### ISSUE THREAD

**Issue by Matt-Heltsley** [peteeckel/netbox-plugin-dns#128]
**Is your feature request related to a problem? Please describe.**
Microsoft Azure DNS has a record type of "AZURE ALIAS" which then references an internal Azure resource.  There are 2 problems. The first problem is that there are 2 Type fields, one is the "AZURE ALIAS" type, the other is either "A" or "CNAME" depending on the way you configured the DNS record.  The second problem is that the "value" field contains "/" "-" "_" and " " and can be really long (200 characters).

**Describe the solution you'd like**
Please add a new record type called "AZURE ALIAS" (since that's what MS calls it when you export a zone file).  Ideally it would have a second "type" field for the A or CNAME options, but it could have that in the "value" field like MX records do with the priority field.  

**Describe alternatives you've considered**
I've been using TXT records (with an additional Tag) for this, but that isn't ideal.   

**Additional context**

**Comment by peteeckel** [comment]
`AZURE ALIAS` is not an RFC compliant RR type. So unless someone convinces the `dnspython` team to allow it, there is no way to allow it.

Even if we find a way to allow it it will create tons of trouble with other DNS servers anyway, so - no way. Sorry.
