### ISSUE TITLE
Nested DNS Zone 'active' field is None when querying a DNS Record

### ISSUE THREAD

**Issue by jepify** [peteeckel/netbox-plugin-dns#132]
**Versions**
NetBox Version: 3.6.4
NetBox DNS Version: 0.19.3
Python Version: 3.11.4

**Describe the bug**
I noticed that when querying for a DNS Record the nested zone has field `active: null` even though the actual DNS Zone has it set to true.

To reproduce i have a DNS Zone which has `active: true` in the API:
```
{
    "id": 8762,
    "url": "<urk>",
    "name": "[demo.com](http://demo.com/)",
    "view": {
        "id": 2,
        "url": "<url>",
        "display": "External",
        "name": "External"
    },
    "display": "[External] [demo.com](http://demo.com/)",
    "nameservers": [],
    "status": "active",
    "description": "",
    "tags": [],
    "created": "2024-01-08T07:37:29.133425Z",
    "last_updated": "2024-01-08T07:38:41.848879Z",
    "default_ttl": 86400,
    "soa_ttl": 86400,
    "soa_mname": {
        "id": 31,
        "url": "<url>",
        "display": "[toby.ns.cloudflare.com](http://toby.ns.cloudflare.com/)",
        "name": "[toby.ns.cloudflare.com](http://toby.ns.cloudflare.com/)"
    },
    "soa_rname": "[demo.com](http://demo.com/)",
    "soa_serial": 1704699522,
    "soa_serial_auto": true,
    "soa_refresh": 172800,
    "soa_retry": 7200,
    "soa_expire": 2592000,
    "soa_minimum": 3600,
    "active": true,
    "custom_fields": {},
    "tenant": null
}
```

I created a DNS record associated with this Zone: 
![image](https://github.com/peteeckel/netbox-plugin-dns/assets/32161326/ac79b662-5659-424a-9f77-b2ff42799b1d)

When i access this Record through the API i get the following:
```
{
    "id": 26751,
    "url": "<url>",
    "zone": {
        "id": 8762,
        "url": "<url>",
        "display": "[External] [demo.com](http://demo.com/)",
        "name": "[demo.com](http://demo.com/)",
        "view": {
            "id": 2,
            "url": "<url>",
            "display": "External",
            "name": "External"
        },
        "status": "active",
        "active": null
    },
    "display": "[record.demo.com](http://record.demo.com/) [A]",
    "type": "A",
    "name": "record",
    "value": "1.2.3.4",
    "status": "active",
    "ttl": null,
    "description": "",
    "tags": [],
    "created": "2024-01-08T07:38:41.629962Z",
    "last_updated": "2024-01-08T07:38:41.629978Z",
    "managed": false,
    "disable_ptr": false,
    "ptr_record": null,
    "address_record": null,
    "active": true,
    "custom_fields": {},
    "tenant": null
}
```
Here the 'active' field in the nested zone is `null`.

**Expected result**
I expect the 'active' in the nested zone to be passed along correctly and thus true or false

**Actual result**
The 'active' field in the nested zone is `null`.

**Screenshots**
```
...
    "comments": "",
    "tags": [],
    "custom_fields": {
        "dns_zone": {
            "id": 8762,
            "url": "https://netbox-host/api/plugins/netbox-dns/zones/8762/",
            "display": "[External] [demo.com](http://demo.com/)",
            "name": "[demo.com](http://demo.com/)",
            "view": {
                "id": 2,
                "url": "https://netbox-host/api/plugins/netbox-dns/views/2/",
                "display": "External",
                "name": "External"
            },
           "status": "active",
            "active": true
        },
        "subnet_host_address": null,
        "infoblox_ref_id": null
    },
    "created": "2022-03-10T00:00:00Z",
...
```
Example of an ip-address with a nested DNS Zone in the custom_field, where the active field is serialized correctly

**Comment by jepify** [comment]
I tested with version `0.21.13` of the plugin and the issue remains

**Comment by peteeckel** [comment]
Thanks, that's an interesting one - I'll need to investigate further why the nested serializer works when used in a custom field but not in another serializer. 

The `active` field is a bit special as it's not a real field but an annotation, and I suspect some peculiarity in Django that the core NetBox implementation somehow worked around. Otherwise there's nothing special about the nested zone serializer.

Might take some time, though, as I'm on vacation for a couple of weeks.

**Comment by jepify** [comment]
Thank you for the reply. I find it strange too, but have noticed that its a derived field which may act wierd in certain cases

**Comment by peteeckel** [comment]
I wouldn't be surprised at it acting weird would it not act non-weird in other cases ... let's see what I can find out.

**Comment by peteeckel** [comment]
A small update (though not a good one): This does not change with the latest NetBox code base (pre-4.0.0). I thought I'd check that out first - lazy guy that I am :-)

**Comment by peteeckel** [comment]
Some more investigation: This is starting to smell like a very strange bug, probably outside of NetBox DNS. Let's see where the NestedZoneSerializer is used ... 

```python
class RecordSerializer(NetBoxModelSerializer):
    [...]
    zone = NestedZoneSerializer(
        many=False,
        required=False,
        help_text="Zone the record belongs to",
    )
    [...]
```

```python
class ZoneSerializer(NetBoxModelSerializer):
    [...]
    rfc2317_parent_zone = NestedZoneSerializer(
        many=False,
        read_only=True,
        required=False,
        help_text="RFC2317 arent zone for the zone",
    )
    rfc2317_child_zones = NestedZoneSerializer(
        many=True,
        read_only=True,
        required=False,
        help_text="RFC2317 child zones of the zone",
    )
    [...]
```

```python
class NameServerSerializer(NetBoxModelSerializer):
    [...]
    zones = NestedZoneSerializer(
        many=True,
        read_only=True,
        required=False,
        default=None,
        help_text="Zones served by the authoritative nameserver",
    )
    [...]
```

That's four places in total. Now let's look at the result of API queries to Record, Zone and NameServer objects, in the same order as above.

```json
  "results": [
    {
      [...]
      "zone": {
        "id": 3,
        "url": "http://192.168.106.105/api/plugins/netbox-dns/zones/3/",
        "display": "0.0.10.in-addr.arpa",
        "name": "0.0.10.in-addr.arpa",
        "view": null,
        "status": "active",
        "active": null,
        "rfc2317_prefix": null
      },
      [...]
```

```json
    {
  "results": [
    {
      [...]
      "rfc2317_parent_zone": {
        "id": 3,
        "url": "http://192.168.106.105/api/plugins/netbox-dns/zones/3/",
        "display": "0.0.10.in-addr.arpa",
        "name": "0.0.10.in-addr.arpa",
        "view": null,
        "status": "active",
        "active": null,
        "rfc2317_prefix": null
      },
      [...]
    },
```

```json
  "results": [
    {
      [...]
      "rfc2317_child_zones": [
        {
          "id": 4,
          "url": "http://192.168.106.105/api/plugins/netbox-dns/zones/4/",
          "display": "0-31.0.0.10.in-addr.arpa",
          "name": "0-31.0.0.10.in-addr.arpa",
          "view": null,
          "status": "active",
          "active": true,
          "rfc2317_prefix": "10.0.0.0/27"
        }
      ],
    },
    [...]
```

```json
{
  "results": [
    {
      [...]
      "zones": [
        {
          "id": 3,
          "url": "http://192.168.106.105/api/plugins/netbox-dns/zones/3/",
          "display": "0.0.10.in-addr.arpa",
          "name": "0.0.10.in-addr.arpa",
          "view": null,
          "status": "active",
          "active": true,
          "rfc2317_prefix": null
        },
        [...]
      ],
      [...]
    },
```

You see the picture? The derived field `active` does not work when `many=False`, but it does when `many=True`. There is no correlation with the value of `read_only` nor with `required`. So the takeaway from that is that it's not the serializer that has the issue but something in the code running it in NetBox or Django.

**Comment by peteeckel** [comment]
A bit more debugging and a solution :-)

It's possible to override the `to_representation()` method of a serializer. That method is responsible for deserializing an object to a dictionary, and its result is then converted to JSON (or whatever is requested) when an API call is made. 

It turns out that the instance passed to `to_representation()` lacks the derived field `active`. This is obviously the reason for the `None` value. Currently I can only speculate why that happens with `many=False` and not with `many=True`, and to be honest I don't have the time to investigate in the `django-rest-framework` code what's the culprit - obviously it doesn't use the `RecordManager` object manager class from `netbox_dns.models`, otherwise the field would be populated.

Anyway, the investigation gave me the idea for a workaround - quite a simple one, to be precise.

**Comment by jepify** [comment]
Very cool finding. I respect that  you don't have the time for looking into the `django` framework :). Great job. I will test the change when i have time for it.
