### ISSUE TITLE
Typo in documentation: tolerate_underscores_in_hostnames

### ISSUE THREAD

**Issue by squintfox** [peteeckel/netbox-plugin-dns#150]
NetBox DNS Version: 0.21.17

**Describe the bug**

There seems to be a typo in the documentation.

https://github.com/peteeckel/netbox-plugin-dns/blob/1f230552fbd93890be370a05d2becfaae238d777/docs/using_netbox_dns.md?plain=1#L448-L449
https://github.com/peteeckel/netbox-plugin-dns/blob/1f230552fbd93890be370a05d2becfaae238d777/docs/using_netbox_dns.md?plain=1#L456-L457
https://github.com/peteeckel/netbox-plugin-dns/blob/1f230552fbd93890be370a05d2becfaae238d777/docs/using_netbox_dns.md?plain=1#L466-L467

However the code seems to use "tolerate_underscores_in_hostnames" instead.  

https://github.com/peteeckel/netbox-plugin-dns/blob/1f230552fbd93890be370a05d2becfaae238d777/netbox_dns/__init__.py#L34-L35
https://github.com/peteeckel/netbox-plugin-dns/blob/1f230552fbd93890be370a05d2becfaae238d777/netbox_dns/validators.py#L23

**Comment by peteeckel** [comment]
Hi @squintfox, you're right, the option name was changed at some point and the documentation wasn't updated. Thanks for reporting!
