### ISSUE TITLE
Add new SOA record

### ISSUE THREAD

**Issue by squintfox** [peteeckel/netbox-plugin-dns#163]
**Versions**
NetBox DNS Version: 0.22.1

This may wind up being more of a question because I'm not sure if it's a bug or not.  Should SOA be a valid record type in the Add new record > Type dropdown?  All the SOA fields are mandatory on the zone object and it automatically creates a managed "@" record (so I get why it should exist as a type).

I'm not a DNS expert, but looking at the RFC, @ or "domain name" are the only valid "owner names" of an SOA record, so what could ever be created manually?

If I'm off base, feel free to close and sorry for the wasted time.

**Comment by peteeckel** [comment]
Hi @squintfox,

> This may wind up being more of a question because I'm not sure if it's a bug or not

Indeed it is not :-)

The SOA record is created automatically from the variables you enter in the SOA section of the zone. Moreover, it contains the SOA SERIAL, which is created automatically which is why the SOA record is updated every time you modify the zone.

That's why SOA is a managed record (i.e. immutable by the user). A second SOA is not permitted anyway (SOA is a singleton), so there should be no need to enter a SOA record manually.

**Comment by squintfox** [comment]
Hey, glad I'm not as dumb as I could have been.  Thanks @peteeckel.

**Comment by peteeckel** [comment]
There's no such thing as a dumb question :-)

That kind of issues lead to gradual improvement ... it just doesn't make sense to allow SOA records to be created manually (and it doesn't work anyway as they are, as I mentioned, singletons), so it's better to remove it from the selection. It's far too long anyway, but in fact that comes from the fact that there is a horribly large number of record types that are standardised although nobody ever uses them.

**Comment by peteeckel** [comment]
As it turns out it's not trivial to remove SOA from the list of types for the selector field but not from the list of types in general ... I'll leave this open for the time being, although it's purely cosmetic. I have a solution, but that one's really, really ugly ...

**Comment by squintfox** [comment]
Maybe just a validation that says name must be @ and you can't have 2?  That way at least the GUI wouldn't allow it to be created.

**Comment by peteeckel** [comment]
The problem with releasing it from the selection is that it's actually needed in there, e.g. for filters and for the model itself. So one (ugly) solution is to create a second `ChoiceSet` that doesn't contain it, purely for entering records manually via the GUI. That's obviously horrible.

There doesn't seem to be a proper way to define a subset of a `ChoiceSet` by removing certain values on the fly, which would be the elegant solution I was looking for. There must be a way, though ... at least that's what I hope.
