### ISSUE TITLE
Change file name of for exported Managed Records.

### ISSUE THREAD

**Issue by KPTheProf** [peteeckel/netbox-plugin-dns#178]
**Is your feature request related to a problem? Please describe.**
An export of the Records is using the same export file name as an export of the Managed Records, netbox_records.csv

**Describe the solution you'd like**
Change Managed Records exported file name to be something else, i.e. netbox_managed_records.csv

**Comment by peteeckel** [comment]
Hi @KPTheProf, I'm afraid this is a NetBox issue - a short search brought up this discussion:

https://github.com/netbox-community/netbox/discussions/12572

If it really hurts you I suggest you open an FR, or at least chime in to the discussion (which unfortunately has been rather quiet). There is nothing I can do about it :-(

**Comment by peteeckel** [comment]
Hi @KPTheProf, I've investigated a bit deeper and yes, it's a NetBox functionality that defines the file name.

From `netbox/views/generic/bulk_views.py`:

```python
    def export_table(self, table, columns=None, filename=None):
        """
        Export all table data in CSV format.

        Args:
            table: The Table instance to export
            columns: A list of specific columns to include. If None, all columns will be exported.
            filename: The name of the file attachment sent to the client. If None, will be determined automatically
                from the queryset model name.
        """
        exclude_columns = {'pk', 'actions'}
        if columns:
            all_columns = [col_name for col_name, _ in table.selected_columns + table.available_columns]
            exclude_columns.update({
                col for col in all_columns if col not in columns
            })
        exporter = TableExport(
            export_format=TableExport.CSV,
            table=table,
            exclude_columns=exclude_columns
        )
        return exporter.response(
            filename=filename or f'netbox_{self.queryset.model._meta.verbose_name_plural}.csv'
        )
```

```python
        if 'export' in request.GET:

            # Export the current table view
            if request.GET['export'] == 'table':
                table = self.get_table(self.queryset, request, has_bulk_actions)
                columns = [name for name, _ in table.selected_columns]
                return self.export_table(table, columns)

            # Render an ExportTemplate
            elif request.GET['export']:
                template = get_object_or_404(ExportTemplate, content_types=content_type, name=request.GET['export'])
                return self.export_template(template, request)

            # Check for YAML export support on the model
            elif hasattr(model, 'to_yaml'):
                response = HttpResponse(self.export_yaml(), content_type='text/yaml')
                filename = 'netbox_{}.yaml'.format(self.queryset.model._meta.verbose_name_plural)
                response['Content-Disposition'] = 'attachment; filename="{}"'.format(filename)
                return response

            # Fall back to default table/YAML export
            else:
                table = self.get_table(self.queryset, request, has_bulk_actions)
                return self.export_table(table)
```

So while `export_table()` generally could be made to export to an arbitrary file, the code in the GET endpoint handler doesn't make use of it, and the code for the YAML export doesn't either.

As a result, the file name is being determined from the model name, and that's `record` for both records and managed records (as they are both objects of the class `netbox_dns.Record`).

**Comment by KPTheProf** [comment]
Hi @peteeckel

Please forgive me as my Python skills are not great, but doesn't this line set the filename when it's passed to the export_table function?

return exporter.response(
            filename=filename or f'netbox_{self.queryset.model._meta.verbose_name_plural}.csv'
        )

**Comment by peteeckel** [comment]
Yes it does. But that doesn't help you, as `export_table` is called by the code below, and without the `filename` option so there is no way to use it. Anyway, that would only help for CSV exports, not YAML, as in the second code segment the `filename` for the YAML export is hard coded as well.
