### ISSUE TITLE
Missed nameservers field when exporting/importing Zones

### ISSUE THREAD

**Issue by samuelet** [peteeckel/netbox-plugin-dns#182]
**Versions**
NetBox Version: 3.7.3
NetBox DNS Version: 0.22.3
Python Version: 3.11.4

**Describe the bug**
Cannot import/export  dns zones nameservers 

**To Reproduce**
1. Go to DNS Configuration -> 'Zones'
2. Click on 'Import' button
3. There is no "nameservers" field in the Zone field list.

**Expected result**
Nameservers field is accepted/present when exporting/importing Zone and it can contains multiple values.

**Actual result**
Nameservers field is not present in import/export field lists, and manually adding the header in the import form prints out the error:  
Record 1: Unrecognized header: namerservers

**Comment by peteeckel** [comment]
Hi @samuelet, thanks for raising this!

I must admit that I don't really see why this is missing - it has been missing from the very first version of NetBox DNS I've worked on, and it's rather obvious that it should be there. Shouldn't be a big deal either ...

**Comment by peteeckel** [comment]
Wasn't a big deal :-)

Thanks again, that was one of the oversights where you ask yourself why nobody ever noticed (including myself).
