### ISSUE TITLE
IP cannot be edited/saved after name and zone assignment

### ISSUE THREAD

**Issue by whtkam** [peteeckel/netbox-plugin-dns#192]
**Versions**
NetBox Version: 3.7.3
NetBox DNS Version: 0.22.4
Python Version: 3.9.11

**Describe the bug**
If you open an IP for editing that already has an A and PTR record assigned and you want to save it, an error message will appear.
Everything is correct the IP, dns_name, cf_ipaddress_dns_record_name, cf_ipaddress_dns_zone_id.
You can change the name and change it back this works. If you don't change it, the error will occurs.

**To Reproduce**
1. Assign  cf_ipaddress_dns_record_name  cf_ipaddress_dns_zone_id to an existing IP address
2. Save works - A and PTR record are created everything looks good.
3. Edit this IP without any change and try to save it.

**Expected result**
Saving should be possible if you want to edit the description, for example.

**Screenshots**
![dns](https://github.com/peteeckel/netbox-plugin-dns/assets/89918174/35e4f565-dabc-4c72-bbea-1853ed61fe96)

**Comment by peteeckel** [comment]
Argh ... I'll look at it ASAP.

Did you just forget to mention that you enabled `enforce_unique_records`, or haven't you done that?

**Comment by whtkam** [comment]
Yes - "force_unique_records" is "True" - If I set it to "False" I can save the IPs

**Comment by peteeckel** [comment]
That's the curse of quickly creating a feature on the fly :-)
