### ISSUE TITLE
Unterscore in DNS entries

### ISSUE THREAD

**Issue by FreQ03** [peteeckel/netbox-plugin-dns#23]
**Is your feature request related to a problem? Please describe.**
Hi Togehter!
I know it is litte issue, nevertheless it would help me quite a lot if we can enable "_" (underscore) for DNS Entries, as far as I know it is already allowed by RFC for some usecases (https://datatracker.ietf.org/doc/html/rfc2782)

**Describe the solution you'd like**
That I can add underscores in DNS Entries

**Describe alternatives you've considered**
maybe also with an "\" before it.

**Additional context**
Thanks :)

**Comment by peteeckel** [comment]
You can do this right now. 

Out of the box, NetBox DNS supports underscores where the underlying RFCs allow them, for example in SRV and TXT records.

If you need to, you can also enable them whereever a dash is supported by using the `allow_underscores_in_hostnames` setting in the PLUGINS_CONFIG` dictionary in `configuration.py`. 

See also the [Validation Options](https://github.com/peteeckel/netbox-plugin-dns/blob/main/docs/using_netbox_dns.md#validation-options) section in the documentation) for more information.

**Comment by peteeckel** [comment]
Did my answer solve your problem or is there anything else I can do for you?

**Comment by FreQ03** [comment]
Hi!I haven‘t tried it for now, nevertheless i think it will solve my problem. Thanks a lot Mario Sent from my iPhoneOn 04.07.2023, at 9:39 AM, Peter Eckel ***@***.***> wrote:﻿
Did my answer solve your problem or is there anything else I can do for you?

**Comment by kollross** [comment]
This didn't appear to have the desired affect.

Adding the below config into configuration.py

```
PLUGINS_CONFIG = {
     'netbox_dns': {
         'allow_underscores_in_hostnames': 'True'
     }
 }
```

And restarting netdot 

```
systemctl daemon-reload
systemctl restart netbox netbox-rq
```

Resulted in the same error in trying to create a hostname with an "_" in the name.
