### ISSUE TITLE
String too long for TXT record

### ISSUE THREAD

**Issue by Serverhamster** [peteeckel/netbox-plugin-dns#269]
**Versions**
NetBox Version: 4.0.2
NetBox DNS Version: 1.0.0
Python Version: 3.10.12

**Describe the bug**
TXT records containing valid DKIM values are too long to add.

Error on saving:
`Record value "v=DKIM1; k=rsa; p=MIIBqhki<...snip...>JPoGa7I" is not a valid value for a TXT record: string too long.`

It is possible to add these long TXT records to the provider's DNS, so I take it that "not a valid value" isn't entirely correct. It is now impossible to store the record in netbox-plugin-dns. My example is 410 characters.

**Comment by Serverhamster** [comment]
You are correct. Thanks for answering this. I should have done my research better. The provider allows a single string, but I see now that the answer section indeed contains 2 strings, and that it is possible to use those 2 strings as input in the plugin.

**Comment by peteeckel** [comment]
I put an item on my mid-term action list: 'Check options to break up long record values into strings of less than 256 octets'. It isn't entirely trivial, though, as you need to take IDNs etc. into account - so don't hold your breath.

**Comment by peteeckel** [comment]
@Serverhamster As you may have seen I've finally managed to address this in a new PR.

Fortunately, IDNs are not an issue here - RFC1035 only allows printable ASCII in TXT records anyway. Let's see when someone comes up with a special case where an SPF record for an IDN domain ... :-)
