### ISSUE TITLE
Add support to move NetBox DNS to plugins submenu

### ISSUE THREAD

**Issue by mjf** [peteeckel/netbox-plugin-dns#295]
With default to `False` let user to reincarnate the current menu placement with:

```python
PLUGINS_CONFIG = {
    'netbox_dns': {
        'top_level_menu': True,
    },
}
```
Plugin supporting this is for example `netbox-acls` (for inspiration).

**Comment by peteeckel** [comment]
Sure, why not. It might make much sense when you have many plugins installed.
