### ISSUE TITLE
Plugin top level menu name

### ISSUE THREAD

**Issue by mjf** [peteeckel/netbox-plugin-dns#296]
I do not prefer the `NetBox DNS` in the top level menu and would like to see just `DNS` there. It would be nice to allow for  either configuring the menu item name or to rename it to just `DNS`. (We all know we are in NetBox when using it.)

**Comment by peteeckel** [comment]
That's a matter of taste, but while I'm at it looking at making the location of the menu item configurable I can as well do the same with the name.

**Comment by peteeckel** [comment]
The plugin will definitely not be renamed, so that's out of the question.

I made the name configurable, but that doesn't play well with your other PR as NetBox uses the verbose name of the plugin by default to create the section label.
