### ISSUE TITLE
Unable to install for Netbox3.7.3

### ISSUE THREAD

**Issue by iqwang** [peteeckel/netbox-plugin-dns#319]
**Versions**
NetBox Version: 3.7.3
NetBox DNS Version: 0.22.9
Python Version: 3.10.12

**Describe the bug**
I followed the detailed instruction:
https://github.com/peteeckel/netbox-plugin-dns/blob/main/docs/using_netbox_dns.md

Even after "pip install 'netbox-plugin-dns<0.23'", it still shows the following error:
django.core.exceptions.ImproperlyConfigured: Plugin netbox_dns requires NetBox minimum version 4.0.0.

Is this plugin still compatible with olcer NetBox versions, i.e < V.4.x?

Thanks.

**Comment by peteeckel** [comment]
Hi @iqwang, could please run 
```
pip freeze | grep netbox-plugin-dns
```
in your venv and post the results here? 

I just checked `__init__.py` to be on the safe side, and the version requirement is definitely correct:
```python
__version__ = "0.22.9"


class DNSConfig(PluginConfig):
    name = "netbox_dns"
    verbose_name = "NetBox DNS"
    description = "NetBox plugin for DNS data"
    min_version = "3.5.0"
    max_version = "3.99.0"
```

**Comment by iqwang** [comment]
Hi, I find out that it needs to specify the version in local_requirements.txt:
netbox-plugin-dns==0.22.9

Now it is successfully installed.
Thanks.
