### ISSUE TITLE
cant save google MXes and TXT size too short to store DKIM value

### ISSUE THREAD

**Issue by abdurrm** [peteeckel/netbox-plugin-dns#33]
**Versions**
NetBox Version: 3.5.6
NetBox DNS Version: 0.18.5
Python Version: 3.10.6

**Describe the bug**
More than one MX record
error TXT value too long to store "DKIM1 rsa key"

**Comment by peteeckel** [comment]
Hi @abdurrm, that's an interesting one ... can you provide a DNS query for this record?

Actually there is a size limit to record values in the database (fields for RR values are limited to 1000 characters). Probably that was a limit imposed in an early version of NetBox DNS, and I'll have to modify the Record model to fix it.

**Comment by peteeckel** [comment]
Hi @abdurrm, I just published version 0.18.6, which fixes the size limit for RR values.

Regarding the MX records I don't see what the problem is, you can provide as many MX records as needed right now. If you still have a problem, please reopen this issue with a detailed description how to reproduce it.

**Comment by abdurrm** [comment]
sorry, my mistake, no issue for duplicate MX record.

but one more, is it forbidden to add "_" character to A record? i have some old record using it.

I am done adding 3000 record, import manually from our PDNS API
it will be great if someone make two way sync between netbox-plugin-dns to powerdns, 

unfortunately this script only allow netbox as the SoT, which is so risky to be run in our big old records.
https://github.com/v0tti/netbox-powerdns-sync

thank you btw, i will find a way to sync

**Comment by peteeckel** [comment]
Hi @abdurrm, thanks for the update.

Normally, underscores in RR names are restricted to some special cases as TXT and SRV records.

You can, however, allow them using a config setting. This came up only recently in issue #23 and is described in detail under [Validation Options](https://github.com/peteeckel/netbox-plugin-dns/blob/main/docs/using_netbox_dns.md#validation-options).

Currently I don't have a custom sync script for PowerDNS, but contributions are welcome :-)
