### ISSUE TITLE
Custom Fields not Saving

### ISSUE THREAD

**Issue by wz4** [peteeckel/netbox-plugin-dns#341]
**Versions**
NetBox Version: 4.0.8
NetBox DNS Version: 1.0.5
Python Version: 3.11.9

**Describe the bug**
I am having an inconsistent problem updating custom fields for DNS records. The problem is happening via GUI and API. It appears that custom fields don't save unless a core field is also updated. The GUI will display a message that changes were saved, then on refresh the old values still exist. The custom field types I am using are text and long text.

**To Reproduce**
1. Create a custom field for DNS Records
2. Attempt to update an object changing only the custom field.
3. Refresh the page and notice value did not change
4. Update 'description' field along with custom field and notice value does change

**Expected result**
Custom fields should be updated on every save

**Actual result**
Custom fields are not saved consistently

**Comment by peteeckel** [comment]
Hi @wz4, thanks for reporting this, I think I have an idea what might be the reason ... will look at it as soon as possible.
