### ISSUE TITLE
Underscores in hostnames. 

### ISSUE THREAD

**Issue by kollross** [peteeckel/netbox-plugin-dns#35]
**Versions**
NetBox Version: 3.5.7
NetBox DNS Version: 0.18.7
Python Version: 3.9.2

**Describe the bug**
For some Security vendors, they are require a DNS entry be created that is a CNAME to another DNS entry that the vendor also generates.

Example:
_08316b4fbe1f4c3180fcf1c6143c2747       86400   IN      CNAME   10fa727fe09ae62087b40e110dac2aef.dac9d20dae4d36fc035c9474a9e62e29.sectigo.com.
_b732317a76b99ea2518103c4963b9b3b       86400   IN      CNAME   1f92b88630ef249b2e84caa2daccf3d9.095004084a42ed3e2959a65a8bd684df.sectigo.com.

I suspect that given the "_" in the hostname netbox-dns will not allow this record to be created.

**To Reproduce**
1. Go to '.Add a new record.'
2. Fill out the correct information.
3. Click Create.
4. Box appears saying "Not a valid DNS host name"

**Expected result**
Allows the creation of the record. 

**Actual result**
Error stating "Not a valid DNS host name"

This seems a bit of a gray area.   From reading, it seems they are not permitted, domain names, but hostnames there seems to be more flexibility.

**Comment by peteeckel** [comment]
Hi @kollross, the issue is not only the underscore, it's that the name actually **starts** with an underscore.

I'm not sure that's allowed for host names at all, but I will check. In the meantime, please use 
```
    'netbox_dns': {
        'tolerate_non_rfc1035_types': ["CNAME"]
    },
```
to allow this kind of name. This disables validation of CNAMEs altogether (use with caution!). If you want to disable validation of address records as well, add `"A"` and/or `"AAAA"` to the list.

**Comment by peteeckel** [comment]
The less radical method is
```
    'netbox_dns': {
        'tolerate_leading_underscore_types': ["SRV", "TXT", "CNAME"]
    }
```
which should do as well for your case.

**Comment by kollross** [comment]
That at least allowed me to create the DNS records.

**Comment by peteeckel** [comment]
Hi @kollross, thanks for the update.

I'm sorry that I didn't see your particular problem at once. The issue of underscores in host names is rather complex, and there are some DNS implementations that won't accept them without explicit configuration. To be on the safe side, NetBox DNS is rather conservative in what you can do in terms of host names, but - as you saw - there are provisions to persuade it to use a more relaxed approach.

The more you read about undercored host names, the more surprising facts you'll find - e.g. [RFC8552](https://www.rfc-editor.org/rfc/rfc8552) has some additional interesting facts I didn't know about. That makes writing a generic host name validator at least very tedious. Not even `dnspython` (which in other respects provides pretty good validation) covers every aspect.
