### ISSUE TITLE
Validation for Rname not complete

### ISSUE THREAD

**Issue by dhoffend** [peteeckel/netbox-plugin-dns#355]
**Versions**
NetBox Version: 4.0.9
NetBox DNS Version: 15451438cafe7ef1b4045dc3115dc0edbc0b3de3)

**Describe the bug**
Validation of RName not complete
https://en.wikipedia.org/wiki/SOA_record

The rname can contain \\. as substitute for . before the @ replacement
Example: john\\.doe.example.com

The field validation says invalid dns record.

**To Reproduce**
1. Create Zone
2. Set RNAME to john\\.doe.example.com
3. Save and see error

**Expected result**
Should be accepted

**Actual result**
john\.doe.example.com is not a valid fully qualified DNS host name

**Comment by peteeckel** [comment]
I can't reproduce this:

<img width="719" alt="Screenshot 2024-08-21 at 13 36 49" src="https://github.com/user-attachments/assets/19bb237f-907f-490e-93b5-1eee94f32dd1">

On the other hand I think I know what you **wanted** to write: `john\.doe.example.com` - correct? Github seems to have swallowed the backslash :-)
