### ISSUE TITLE
IPAM Coupling: Set the dns name field to read-only.

### ISSUE THREAD

**Issue by poupryc** [peteeckel/netbox-plugin-dns#363]
Since the IPAM coupling overrides the DNS name in the details pane, it would be logical to make this field read-only if possible, to prevent accidental edits that wouldn't have any effect but could triggers webhook action.

**Describe the solution you'd like**
DNS name is now read-only after running `/opt/netbox/netbox/manage.py setup_coupling`

**Comment by peteeckel** [comment]
Hi @poupryc, thanks for your input.

Unfortunately the `dns_name` field is a field of the NetBox core `ipam.IPAddress` model, so I can't make it read-only. There would be the option of adding validators to achieve that goal, but it's not the same and would confuse users.

Anyway, IPAM Coupling is deprecated and will be gone soon, and the new feature "IPAM DNSsync" actually makes use of the value you enter in the `dns_name` field, so the confusion will be gone soon. See the discussion in #340.

**Comment by poupryc** [comment]
@peteeckel thanks for the clarification ;) can't wait for 4.1 then

**Comment by poupryc** [comment]
Will wait for the stable version to drop ;)

I don't think a migration path is necessary given the minority of people using the current implementation.

On the other hand, I think it's important to just write how to revert and remove changes to the database related to the IPAM coupling (I think simply by using `/opt/netbox/netbox/manage.py setup_coupling --remove`).

Thanks for your work!

**Comment by peteeckel** [comment]
> I don't think a migration path is necessary given the minority of people using the current implementation.

You'd be surprised ... just look at the issues since coupling came out. There is a certain demand for that kind of feature.

> On the other hand, I think it's important to just write how to revert and remove changes to the database related to the IPAM coupling (I think simply by using /opt/netbox/netbox/manage.py setup_coupling --remove).

It's all in the docs. Essentially `setup_dnssync` takes care of changing the old custom fields (if they exist). Fortunately I could retain all the database structures for the new feature, so there is no migration (and no loss of existing data).

You're welcome - It's part fun, part business and part self-castigation :-)

**Comment by peteeckel** [comment]
According to the NetBox project's GitHub page, the release of NetBox 4.1 is planned for September 1st.

I am constantly running tests against new pushes to `feature` and haven't had a single 4.1-related issue over the last weeks, so I expect you don't have to wait much longer.
