### ISSUE TITLE
Unable to create an MX record

### ISSUE THREAD

**Issue by BarrieAlmond** [peteeckel/netbox-plugin-dns#417]
**Versions**
NetBox Version: 4.1.1
NetBox DNS Version: 1.1.3
Python Version: 3.11.7

When creating an MX record, I'm not sure what to enter in the Value field. Whatever I seem to do returns the form with an error message under that field. I'm also not sure where to enter a priority if that is possible.

**To Reproduce**
1. Go to Add a new record
2. Enter @ for name
3. Choose a view, zone, and set the record type to MX
4. If you enter an IP address or server name for the Value and save you get the message :

Record value mail.server.com is not a valid value for a MX record: expecting an integer.

If you enter an integer and try to save you get the message:

Record value 10 is not a valid value for a MX record: expecting an identifier. 

**Expected result**
To be able to save an MX record pointing to a mail server and set a priority value.

**Actual result**
The form is returned with a red error message under the value field.

**Comment by peteeckel** [comment]
The value of an MX record consists of an integer (the priority), followed by the name of the mail server.
