### ISSUE TITLE
Wildcard records not accepted. 

### ISSUE THREAD

**Issue by kollross** [peteeckel/netbox-plugin-dns#45]
**Versions**
NetBox Version: 0.18.7
NetBox DNS Version: 3.5.7
Python Version: 3.9

**Describe the bug**
Creating Wildcard DNS records (example:  *.test.example.com) fails inside Netbox-DNS.   Error indicates that it is not a valid hostname. 

**To Reproduce**
1. Click the + sign to add new record. 
2. put into *.test into the name field
3. select the correct zone.
4. Select type "A" record, and enter the correct value.

**Expected result**
DNS record be created. 

**Actual result**
Error message saying it is not a valid host.

**Comment by peteeckel** [comment]
Good one :-)

Actually you can create `*`, but not `*.test`. That should work ... let me see.

**Comment by peteeckel** [comment]
The issue was actually that the validation code did not accept wildcard names including additional labels, which it should. I'll deploy a new release shortly.

**Comment by peteeckel** [comment]
0.18.8 is out.

Thanks for reporting this!

**Comment by kollross** [comment]
I upgraded to 0.18.8, but instead of the CSS style error, I takes me to a new error page.  
![Screenshot 2023-08-04 at 10 16 06 AM](https://github.com/peteeckel/netbox-plugin-dns/assets/1349642/056bc19a-fdd5-4d62-823c-e3c678a3946b)

**Comment by peteeckel** [comment]
Can you please enable debugging and send me the call stack? I can't reproduce it here.

**Comment by peteeckel** [comment]
I see where it happens - you are creating PTR records automatically, aren't you? The error occurs when creating the PTR record, and that doesn't happen in the view - hence the `ServerError` instead of CSS.

Fix is on the way, I just need to create some tests for this case.

**Comment by peteeckel** [comment]
-> 0.18.9
