### ISSUE TITLE
Rebuild DNS Managed Record

### ISSUE THREAD

**Issue by shakin89** [peteeckel/netbox-plugin-dns#480]
**Versions**
NetBox Version: 4.1.6
NetBox DNS Version: branch main
Python Version: 3.11.2

**Describe the bug**
Well, i think it's still related to #472.
Yesterday i was investigatin why my webhook didn't fire on updating an ip-dns address. I noticed netbox-dns didn't update records, so i made a cleanup_rrset, a setup_dnssync and a rebuild_dnssync. 
Well, these commands deleted all my managed Records. So i came here to gh to lokk for an open bug and i found #472.
I manually upgraded netbox-plugin-dns from gh branch main, made again a rebuild_dnssync but i still have no managed records.
If i try to create a new record, these won't appear in managed record list.
I tried even to reinstall whole netbox and netbox-plugin-dns making all migrations, but even this didn't work.
Any hint ans suggestion would be very appreciated.
And yes, i've got custom fields both in ip addresses and on dns names.
Thanks again for your great work and tell me how i can provide some more detailed logs.

**Screenshots**
![Screenshot 2024-11-20 083058](https://github.com/user-attachments/assets/f2c7a494-6063-444b-827d-9a06b6f32878)
![Screenshot 2024-11-20 083120](https://github.com/user-attachments/assets/8c9c5694-e0fb-4e28-a1db-99bcfb7ca66c)

This is the log from rebuild_dnssync
Updating DNS records for IP Address 172.30.10.1/32, VRF None
Updating DNS records for IP Address 172.30.10.2/32, VRF None
Updating DNS records for IP Address 172.30.10.3/24, VRF None

**Comment by peteeckel** [comment]
Hi @shakin89, thanks for your report. Let's try to tackle your issue systematically. There is some information that's missing.

I assume you are using NetBox DNS to synchronise IPAM IP addresses to DNS A records, and the managed records that are missing are the records created for IP addresses, correct? In this case, let's rule out some of the possible causes:

1. It's definiteny **not** linked to #472. That issue dealt with custom fields for zones and records, not IP addresses.
2. `cleanup_rrset` is not linked to this either, it just deals with TTLs across RRsets.

So the problem is probably in IPAM DNSsync, and I have the strong suspicion (from your focus to custom fields) that you upgraded from NetBox DNS 1.0.x to NetBox DNS 1.1.x when the error occurred. Is that correct?

NetBox DNS 1.0.x had an experimental feature named "IPAM Coupling" that linked DNS records to IP addresses by means of setting custom fields on the IP addresses to assign a host name and a zone per IP address. This feature was removed in NetBox DNS 1.1.0 and replaced by the more flexible "IPAM DNSsync", which works in a very different way.

If I'm correct in that assumption, please have a look at https://github.com/peteeckel/netbox-plugin-dns/blob/main/docs/using_netbox_dns.md#migration-from-ipam-coupling (and generally at the documentation regarding IPAM integration). If I'm not, please update what exactly you're doing to get DNS managed records that are missing.

**Comment by shakin89** [comment]
Well, firt of all thanks for your support. 

Your assumption are correct, I use netbox to manage ip address of devices and to synchronize them with A record. After every update of a record, an ansible script is launched with a webhook to update bind zone and kea dhcp persistent lease. So the missing managed records are those created for ip address.

Migrating from netbox 3.x to 4.0.x i followed your guide, launching every command to migrate from ipam coupling to dnssync. 
I've associated my view with ipam prefixes (i've got only 4x256 ip address so the migration has been very quick).

Now, digging a little bit deeper, my eyes has fallen on zone registry
![Zone Registry](https://github.com/user-attachments/assets/ba4fd092-f07a-4659-9c4a-d20a4ebb8df0)

As you can see yesterday i've updated an ip address and the related A record was updated.
I've done the same thing now and no modification is reported.

Just yesterday evening, after 6pm i've upgraded to netbox 4.1.6.
Trying to downgrade to 4.1.3 (the working version) to see if that was the problem.

**Comment by peteeckel** [comment]
Let's try it systematically.

1. Go to one of the IP addresses, select (preferably the closest) IP prefix of that address and check whether a view is associated with that IP address
2. Check that the zone you expect the record to be created in actually is present in that view (you can navigate to the view's detail page and look at the 'Zones' tab.
3. If it is, look at the managed records to make sure the record isn't there.
4. Then, go back to the IP address, edit and save it immediately after. Just as an experiment, you can change the DNS name field to a different host name within the zone.
5. Check the zone for managed records again. If the record appears now, we have a better idea where to look.

Generally, there are tons of automated tests that validate the record generation, so it's improbably that there is a general problem with the record generation. It can, however, be the case that some optimisation takes place when you enter data in the GUI that might inhibit updating (or, in this case, creating) a new address record.

**Comment by shakin89** [comment]
> Let's try it systematically.
> 
> 1. Go to one of the IP addresses, select (preferably the closest) IP prefix of that address and check whether a view is associated with that IP address
Done
![view](https://github.com/user-attachments/assets/3913567a-b38d-46ca-b986-f20c91f3e29e)

> 2. Check that the zone you expect the record to be created in actually is present in that view (you can navigate to the view's detail page and look at the 'Zones' tab.
![Zone](https://github.com/user-attachments/assets/bb67c2a6-20a3-47c7-ad8c-27ba74c85b03)

> 3. If it is, look at the managed records to make sure the record isn't there.
i've no more managed records in here, has been deleted when i've done rebuild_dnssync yesterday
![Managed Records](https://github.com/user-attachments/assets/ff7b0b0c-d9ce-4562-9e17-2196b2e2cdd1)

> 4. Then, go back to the IP address, edit and save it immediately after. Just as an experiment, you can change the DNS name field to a different host name within the zone.
![before insert](https://github.com/user-attachments/assets/32ef45af-847f-4759-8e2b-fd263a2fdb73)
![Screenshot 2024-11-20 141541](https://github.com/user-attachments/assets/7bb5f672-07f1-47ec-8fba-e1841faf55fd)
![Screenshot 2024-11-20 141550](https://github.com/user-attachments/assets/64d9cdbf-c1cb-46da-a02f-e384a7b635fc)


> 5. Check the zone for managed records again. If the record appears now, we have a better idea where to look.
![Screenshot 2024-11-20 141746](https://github.com/user-attachments/assets/de0bf937-2ab3-4c71-9e09-14a18cb1525d)

No records are showing. Seems like it doesnt catch the save signal from ipam

this is the log from netbox in INFO level. The DEBUG level generates a ton of message regarding uncatched variables in templates (about >10k lines for this simple operation)

```log
2024-11-20 14:03:50,628 netbox.views.ObjectDeleteView INFO object_views 2720 133610764531520 Deleted indirizzo IP 172.30.10.3/32
2024-11-20 14:04:50,125 netbox.views.ObjectEditView INFO object_views 2720 133610764531520 Modified Visualizza internal (PK: 1)
2024-11-20 14:05:04,680 netbox.views.ObjectEditView INFO object_views 2721 133610764531520 Modified Visualizza internal (PK: 1)
2024-11-20 14:07:24,448 netbox.views.ObjectEditView INFO object_views 2721 133610764531520 Modified Zone [internal] mgmt.shakxxx(PK: 2)
2024-11-20 14:08:17,661 netbox.views.ObjectEditView INFO object_views 2723 133610764531520 Created indirizzo IP 172.30.10.3/32 (PK: 229)
2024-11-20 14:14:15,362 netbox.views.BulkDeleteView INFO bulk_views 2723 133610764531520 Eliminato 1 Indirizzi IP
2024-11-20 14:17:11,605 netbox.views.ObjectEditView INFO object_views 2720 133610764531520 Created indirizzo IP 172.30.10.3/32 (PK: 230)
2024-11-20 14:17:31,510 netbox.views.ObjectEditView INFO object_views 2722 133610764531520 Modified Zone [internal] mgmt.shakxxx (PK: 2)
```

> Generally, there are tons of automated tests that validate the record generation, so it's improbable that there is a general problem with the record generation. It can, however, be the case that some optimisation takes place when you enter data in the GUI that might inhibit updating (or, in this case, creating) a new address record.

Well, again thanks for your patience to help me trying to understand where's the problem.

**Comment by peteeckel** [comment]
I just pushed a new version of the `rebuild_dnssync` command that will give you the list of matching zones when running `rebuild_dnssync`. Please try it out to see if any zones are selected at all for your IP addresses. There should be something like 
```
(netbox) [root@dns netbox]# /opt/netbox/netbox/manage.py rebuild_dnssync -v3
Updating DNS records for IP Address 10.0.0.1/24, VRF None
  Zones: [<Zone: zone1.example.com>, <Zone: [external] zone1.example.com>, <Zone: [test2] zone1.example.com>]
Updating DNS records for IP Address 10.0.0.2/24, VRF None
  Zones: [<Zone: zone1.example.com>, <Zone: [external] zone1.example.com>, <Zone: [test2] zone1.example.com>]
Updating DNS records for IP Address 10.0.0.3/24, VRF None
  Zones: [<Zone: zone1.example.com>, <Zone: [external] zone1.example.com>, <Zone: [test2] zone1.example.com>]
```
when you run it, as opposed to 
```
Updating DNS records for IP Address 10.1.1.2/24, VRF None
  Zones: []
Updating DNS records for IP Address 10.1.1.3/24, VRF None
  Zones: []
Updating DNS records for IP Address 10.1.1.3/24, VRF None
  Zones: []
```
if there are no matching zones. That will help us to narrow down the issue.

**Comment by shakin89** [comment]
hi pete, sorry for late reply and thank you for helping in debugging this. 
I've pulled the new branch and this is the output of rebuild_dnssync
```
Updating DNS records for IP Address 172.30.10.1/32, VRF None
  Zones: []
Updating DNS records for IP Address 172.30.10.2/32, VRF None
  Zones: []
Updating DNS records for IP Address 172.30.10.3/32, VRF None
  Zones: []
Updating DNS records for IP Address 172.30.10.4/32, VRF None
  Zones: []
```

this is my plugin config
```python
PLUGINS = ["netbox_dns"]
PLUGINS_CONFIG = {
    "netbox_dns": {
        "tolerate_underscores_in_hostnames": true,
        "tolerate_non_rfc1035_types": ["X25"],
        "enforce_unique_records": true,
        "zone_active_status": [
            "ZoneStatusChoices.STATUS_ACTIVE",
            "ZoneStatusChoices.STATUS_DYNAMIC",
        ],
        "record_active_status": ["RecordStatusChoices.STATUS_ACTIVE"],
        "dnssync_ipaddress_active_status": [
            "IPAddressStatusChoices.STATUS_ACTIVE",
            "IPAddressStatusChoices.STATUS_RESERVED",
            "IPAddressStatusChoices.STATUS_DHCP",
        ],
    }
}
```

**Comment by peteeckel** [comment]
Thanks. That narrows it down quite a bit. Apparently NetBox DNS can't match a zone name to your DNS names.

Can you confirm that the setting in 'DNS Name' is ending in the zone name? E.g. 'zone.example.com' (without a trailing dot)? The names must match exactly for the zone to be found.

If this is not the issue we'll ned to run some checks in `nb_shell`.

**Comment by shakin89** [comment]
I confirm the zone name is mgmt.shak.xxx as you can see from the second screenshot [here](https://github.com/peteeckel/netbox-plugin-dns/issues/480#issuecomment-2488570953).
The zone name doesn't include a trailing dot. 
The DNS name associated with the IP Addres does not include the trailing dot and is in the format name.mgmt.shak.xx

I'm trying to remember what i've done before everything broke down, but it seems i didn't do anything so dangerous. 
As i told you before, i use a webhook to fire an ansible playbook to update the dns zone managed by bind (fired from a create/update/delete of a netbox dns record) and to update the dhcp leases managed by KEA (fired from ip address create/update/delete). I saw the dns playbook didn't play, so i started investigating and arrived here.

**Comment by shakin89** [comment]
I confirm the zone name is mgmt.shak.xxx as you can see from the second screenshot [here](https://github.com/peteeckel/netbox-plugin-dns/issues/480#issuecomment-2488570953).
The zone name doesn't include a trailing dot. 
The DNS name associated with the IP Addres does not include the trailing dot and is in the format name.mgmt.shak.xx

I'm trying to remember what i've done before everything broke down, but it seems i didn't do anything so dangerous. 
As i told you before, i use a webhook to fire an ansible playbook to update the dns zone managed by bind (fired from a create/update/delete of a netbox dns record) and to update the dhcp leases managed by KEA (fired from ip address create/update/delete). I saw the dns playbook didn't play, so i started investigating and arrived here.

**Comment by peteeckel** [comment]
I don't think it's anything you've done but rather some weird circumstances. So far I can't find anything that you might have done wrong. I'm still trying to figure out what actually happens.

Let's try `nbshell`.

Please open an `nbshell` session:
```
[root@dns ~]# . /opt/netbox/venv/bin/activate
(netbox) [root@dns ~]# /opt/netbox/netbox/manage.py nbshell
### NetBox interactive shell (dns.dev.hindenburgring.com)
### Python 3.11.5 | Django 5.0.9 | NetBox NetBox Community v4.1.6
### lsmodels() will show available models. Use help(<model>) for more info.
>>> 
```
Now we can look at the process in detail. 
```python
from netbox_dns.utilities.ipam_dnssync import _get_assigned_views

address = IPAddress.objects.get(address="172.30.10.1/32")
_get_assigned_views(address)
```
This should give you a list of views assigned to the prefix the address is located in. I assume that the list is empty (which is wrong, it should consist of the view "internal"), but that's only an assumption, so please run the test anyway.

Now I would like to drill down on the view assignment process a bit further:
```python
Prefix.objects.filter(
    vrf=address.vrf,
    prefix__net_contains_or_equals=str(address.address.ip),
    netbox_dns_views__isnull=False,
)
```
This should give you the list of all prefixes the address is located in **and** that have an assigned DNS view. If it is empty there's something wrong with the DNS view assignment.

**Comment by peteeckel** [comment]
An additional check you can run is (still in `nbshell`):
```python
from netbox_dns.utilities import get_parent_zone_names

get_parent_zone_names(address.dns_name)
```
This gives you a list of all parent zones that could contain the record (excluding the top level zone, which is normally not in scope).

If this works we can try to find the actual zone (it may return more than the zone we need, but that's fine):
```
Zone.objects.filter(
    name__in=get_parent_zone_names(address.dns_name),
    active=True,
)
```

**Comment by shakin89** [comment]
Holy sh33t!!! What a stupid things i've done! 
When i updated netbox i also updated the configuration and i couldn't remember cause i was focusing on the version upgrade!
Well, i knew it wasn't a bug, i was the bug! :)
I really don't know how to thank you! 
I confirm you the configuration was the problem. 
I've done a rebuild_dnssync and know everything is in the correct place!

**Comment by peteeckel** [comment]
Glad I could help - thanks for raising this, it definitely was a good issue that led to an improvement in the docs.
