### ISSUE TITLE
ImportError: cannot import name 'get_plugin_config' from 'extras.plugins' when updating to netbox 3.5.8

### ISSUE THREAD

**Issue by JohannesKreuzer** [peteeckel/netbox-plugin-dns#49]
**Versions**
NetBox Version: 3.5.8
NetBox DNS Version: 0.18.9

**Describe the bug**
ImportError: cannot import name 'get_plugin_config' from 'extras.plugins' when updating to netbox 3.5.8

Commit f5a1f83f9fa9d98c945d21eb0f7ccb8cd37fbf59 in netbox moved get_plugin_config to extras.plugins.utils

**Comment by peteeckel** [comment]
Hi @JohannesKreuzer, thanks for reporting this issue.

I just released version 0.18.10 to resolve this. Note that starting with this release NetBox 3.5.8 is now the minimum version supported by NetBox DNS.
