### ISSUE TITLE
Error running migration after installation of NetBox and NetBox DNS

### ISSUE THREAD

**Issue by bladerock5** [peteeckel/netbox-plugin-dns#52]
**Versions**
NetBox Version: 3.5.8
NetBox DNS Version: 0.18.10
Python Version: 3.8.10

**Describe the bug**
everything according to the instructions
after executing the command
./manage.py migrate
error message
![1](https://github.com/peteeckel/netbox-plugin-dns/assets/142829322/0d9b8250-d90e-41b0-96bc-0b9695208e3e)

**Comment by peteeckel** [comment]
Hi @bladerock5, thanks for reporting this.

Since this is a very basic error and did not occur anywhere else yet (including in the test procedures) I suspect some issue with your configuration.

Can you please post the plugin-related parts of your NetBox `configuration.py` file?

Was this a fresh install or an upgrade, possibly from NetBox < 3.5.0? If the latter is the case, could it be that the `netbox-dns` PyPI module is still installed in your venv? I don't think that would cause this issue, but I'm not sure and removing it is the clean way anyway.

**Comment by bladerock5** [comment]
Hi
![Screenshot_20230822_092901](https://github.com/peteeckel/netbox-plugin-dns/assets/142829322/f3ef28ae-8de5-403d-804a-f76ab585c264)
![Screenshot_20230822_093016](https://github.com/peteeckel/netbox-plugin-dns/assets/142829322/fc16a0d3-0448-43bc-8dc4-8217a63047d0)
![Screenshot_20230822_093134](https://github.com/peteeckel/netbox-plugin-dns/assets/142829322/a9fe7b24-ccc1-4033-a5f8-3fe4c1405649)
![Screenshot_20230822_093256](https://github.com/peteeckel/netbox-plugin-dns/assets/142829322/215bd653-6804-406d-8263-71b62645e4a2)
,
ran the commands in the following order:

$ source /opt/netbox/venv/bin/activate
(venv) $ pip install netbox-plugin-dns

Add the plugin to the NetBox config. ~/netbox/configuration.py :
PLUGINS = [
    "netbox_dns",
]

created a file (it didn't exist):

nano ~/netbox/local_requirements.txt

add in file text:

netbox-plugin-dns

and saved.

without leaving (venv) fulfilled:

./manage.py migrate

PS:
plugin 'netbox-bgp' installed for testing, I thought that netbox does not work correctly with plugins

**Comment by peteeckel** [comment]
Looks very good.

Could you please look into the file `/opt/netbox/venv/lib/python3.8/site-packages/netbox_dns/__init__.py`?

It **should** look like this:
```
from extras.plugins import PluginConfig

__version__ = "0.18.10"


class DNSConfig(PluginConfig):
    name = "netbox_dns"
    verbose_name = "NetBox DNS"
    description = "NetBox plugin for DNS data"
    min_version = "3.5.8"
    version = __version__
    author = "Peter Eckel"
    author_email = "pe-netbox-plugin-dns@hindenburgring.com"
    required_settings = []
    default_settings = {
        "zone_default_ttl": 86400,
        "zone_soa_serial_auto": True,
        "zone_soa_serial": 1,
        "zone_soa_refresh": 172800,
        "zone_soa_retry": 7200,
        "zone_soa_expire": 2592000,
        "zone_soa_minimum": 3600,
        "feature_ipam_integration": False,
        "tolerate_underscores_in_hostnames": False,
        "tolerate_leading_underscore_types": [
            "TXT",
            "SRV",
        ],
        "tolerate_non_rfc1035_types": [],
        "enable_root_zones": False,
        "enforce_unique_records": False,
    }
    base_url = "netbox-dns"


config = DNSConfig
```

**Comment by peteeckel** [comment]
Another test you can perform is by using `nbshell`:

```
$ source /opt/netbox/venv/bin/activate
$ /opt/netbox/netbox/manage.py nbshell
### NetBox interactive shell (dns.dev.hindenburgring.com)
### Python 3.8.13 | Django 4.1.10 | NetBox 3.5.8
### lsmodels() will show available models. Use help(<model>) for more info.
>>> import netbox_dns
>>> dir(netbox_dns)
['DNSConfig', 'PluginConfig', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'api', 'config', 'fields', 'filters', 'forms', 'graphql', 'models', 'navigation', 'tables', 'template_content', 'templatetags', 'urls', 'utilities', 'validators', 'views']
>>> from netbox_dns import config 
>>> config 
<class 'netbox_dns.DNSConfig'>
>>> config.__dict__
mappingproxy({'__module__': 'netbox_dns', 'name': 'netbox_dns', 'verbose_name': 'NetBox DNS', 'description': 'NetBox plugin for DNS data', 'min_version': '3.5.8', 'version': '0.18.10', 'author': 'Peter Eckel', 'author_email': 'pe-netbox-plugin-dns@hindenburgring.com', 'required_settings': [], 'default_settings': {'zone_default_ttl': 86400, 'zone_soa_serial_auto': True, 'zone_soa_serial': 1, 'zone_soa_refresh': 172800, 'zone_soa_retry': 7200, 'zone_soa_expire': 2592000, 'zone_soa_minimum': 3600, 'feature_ipam_integration': False, 'tolerate_underscores_in_hostnames': False, 'tolerate_leading_underscore_types': ['TXT', 'SRV'], 'tolerate_non_rfc1035_types': [], 'enable_root_zones': False, 'enforce_unique_records': False}, 'base_url': 'netbox-dns', '__doc__': None})
```

If any of these steps fails there is a problem importing `netbox_dns`, or `netbox_dns.config` cannot be accessed for some reason. The exception should hopefully give us a hint what's wrong.

**Comment by bladerock5** [comment]
Hi,
did not wait for your answer, reinstalled netbox.
Installed only 1 plugin netbox-plugin-dns.
Plugin installed successfully, netbox works.
I will try to re-install the plugin on other netbox versions.
Thank you for your time.
![5](https://github.com/peteeckel/netbox-plugin-dns/assets/142829322/e42d2123-b5e2-44ad-82f4-46826c064632)

**Comment by peteeckel** [comment]
Glad it works for you now. Is it OK fir you to close this issue?

**Comment by bladerock5** [comment]
yes
