### ISSUE TITLE
Page button on Zone Records tab not working

### ISSUE THREAD

**Issue by peterbaumert** [peteeckel/netbox-plugin-dns#6]
When i go to
NetBox DNS > Zones > (choose a zone) > Records tab
and then click on the Page 2 or "next" nothing happens.

![image](https://github.com/peteeckel/netbox-plugin-dns/assets/1212934/efb05d36-20a6-48eb-884b-7b6ea3f339d0)

Seems like
```
<div class="card-body" id="object_list">
</div>
```

should be
```
<div class="card-body htmx-container" id="object_list">
</div>
```

**Comment by peteeckel** [comment]
Hi @peterbaumert, thanks for raising this - it worked in NetBox 3.4.x/NetBox DNS 0.17.0, but I remember some mention in the release notes of NetBox 3.5 that referred to changes in some templates of NetBox and HTMX.

Unfortunately (or fortunately, depending on how you look at it :-)) I'm currently on vacation, so it might take me a couple of days to verify this and prepare a new release. I'll probably have to scrutinise all other templates for reoccurrences of the same issue.
