### ISSUE TITLE
IPAM-DNS coupling

### ISSUE THREAD

**Issue by jean1** [peteeckel/netbox-plugin-dns#67]
**Problem statement**
We need consistency between IP addresses and names:
- when adding an IP address, a  (A or AAAA) DNS record must be created.
- when deleting and IP address, the corresponding DNS record must be deleted.

**Approach**
The solution is based on three additional fields associated with the IP Address, "name", "zone" and "dns_record". When we submit the form or post data to the API, both the IP address and the DNS record are created, and the "dns_record" field points to the record. Ditto for deleting the IP Address with a linked DNS record.

**Alternatives**
As an alternative, I have considered using the "dns_name" field. Using this field entails several problems:
- it is only an informative field,
- as a character string, there is no possibility to use the Zone object,
- there is no way to enforce permissions on DNS objects (Zone, Records),
- finally, there is no guarantee of consistency between DNS records and IP addresses.

**Comment by peteeckel** [comment]
Hi @jean1, I just release version 0.20.0, which mainly adds your new feature. Thank you very much for this!

**Comment by peteeckel** [comment]
Hi @jean1, after another round of commits (this time abandoning the middleware concept altogether) I think the experimental feature should be generally working, even with custom scripts (see issue #105).

I'm planning on some enhancements (making the automatism more general and more comfortable), but for the time being this looks pretty useful to me. Thank you very much again for your help!
