### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by tchmnkyz** [peteeckel/netbox-plugin-dns#70]
I am working to automate a little bit and i can not seem to find the proper URL to add a new zone/record. I am using: 

/api/plugins/netbox-dns/zones/add/

Trying both PUT (404 not found) and POST (405 Method Not Allowed). What is the proper URL to get this to work?

**Comment by peteeckel** [comment]
Hi @tchmnkyz, the API used by NetBox (and, by inheritance, NetBox DNS) is REST-API, and as such there is no specific endpoint for actions like 'add'. So the right URI is `/api/plugins/netbox-dns/zones/`, without the `add` at the end.

You can get the full Swagger documentation of the API by clicking on the 'Rest API Documentation' icon at the bottom of the page:
![Untitled](https://github.com/peteeckel/netbox-plugin-dns/assets/6815386/aebe9a94-52f1-4089-9891-6f659f0ac82d)

In Swagger, you can also run API calls and test the results.

**Comment by tchmnkyz** [comment]
Thank you for that!
