### ISSUE TITLE
PTR "managed records" are not removed. 

### ISSUE THREAD

**Issue by kollross** [peteeckel/netbox-plugin-dns#97]
**Versions**
NetBox Version: 3.6.5
NetBox DNS Version: 0.21.0
Python Version: 3.10.12

**Describe the bug**
When removing a managed DNS record "name" and "zone"  for "managed records" then PTR record is not removed. 

**To Reproduce**
1. Pick an IP address
2. Populate the "Custom Fields -> "Name" and "Zone" 
3. Save.
4. Edit the same IP
5. Delete the "Custom Fields" -> "Name" and "Zone"
6. Save

**Expected result**
Clearing the Custom Fields "Name" and "Zone" fields under IP address, properly delete the "A" record under managed records, and the PTR record.  

**Actual result**
Clearing the Custom Fields "Name" and "Zone" fields under IP address, properly delete the "A" record under managed records, but not the PTR record.  Creating a new record will create duplicate PTR record for the same IP.  Also given they are "managed records" I have no way of clearing the stale and duplicate PTR records.   

**Screenshots**

**Code Examples**
If applicable, please provide ideally minimal code example of code that is causing the problem to happen. The more concise the example is, the less effort it is to find a problem.

**Comment by peteeckel** [comment]
Hi @kollross, thanks for reporting this.

I will look into it as soon as I can, but probably not before the weekend. Shouldn't be a big deal.

**Comment by peteeckel** [comment]
Hi @kollross, found and fixed this rather quickly.

However, in fixing it it turns out that the middleware approach to the implementation of the IPAM integration probably doesn't hold, as it doesn't work in the general case. I'm hopeful that it's possible to salvage the general functionality, but this is a good example why this feature was labeled 'experimental' ... :-(

**Comment by kollross** [comment]
Is that do to the nature of how I was using it?  (i.e. clearing the information vs creating/deleting an IP, or some other work flow?)

**Comment by peteeckel** [comment]
No, your workflow is fine. The issue is more about the implementation, which doesn't cover some cases - nothing to do with your issue, actually.

**Comment by kollross** [comment]
I verified that the changes work, so that's good.   I noticed I still have all these stale entries from when I was testing things yesterday with out any clear way of deleting those.   Know of a good way to do that before I start going into the DB?

**Comment by peteeckel** [comment]
Hi @kollross, are you familiar with PostgreSQL? If so I can pin together a little SQL query that should rid you of the PTR records.

**Comment by kollross** [comment]
Yeah, enough to get by.

**Comment by peteeckel** [comment]
OK, do the following:

* Start a DB shell (`/opt/netbox/netbox/manage.py dbshell`) with the NetBox venv enabled
* Check whether the following query returns the `PTR` records you want to delete:

```
SELECT * FROM netbox_dns_record 
   WHERE managed 
   AND type='PTR' AND id NOT IN (
       SELECT ptr_record_id FROM netbox_dns_record
    );
```

* If that's fine, run almost the same query to delete them:

```
DELETE FROM netbox_dns_record 
   WHERE managed 
   AND type='PTR' AND id NOT IN (
       SELECT ptr_record_id FROM netbox_dns_record
    );
```

**Comment by kollross** [comment]
zero rows returned.

**Comment by kollross** [comment]
I didn't have that many records in this state (<10) so I just manually deleted them each by hand.

`delete from netbox_dns_record where id=87006;`
